[package]
name = "tiny-md-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
diffy = { version = "=0.4.2", default-features = false }
gpui.workspace = true
guise.workspace = true
unicode-segmentation = "1.13"
mermaid-rs-renderer = { version = "=0.3.1", default-features = false }
syntect = { version = "=5.3.0", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
