use gpui::*;

actions!(
    tiny_md,
    [
        NewDocument,
        NewWindow,
        OpenDocument,
        SaveDocument,
        SaveDocumentAs,
        ReloadDocument,
        RevealDocument,
        CloseDocument,
        QuitApplication,
        About,
        Hide,
        HideOthers,
        ShowAll,
        Recent1,
        Recent2,
        Recent3,
        Recent4,
        Recent5,
        ToggleSource,
        ToggleTheme,
        LightTheme,
        DarkTheme,
        ToggleSidebar,
        ShowDocuments,
        ShowOutline,
        ShowTree,
        OpenFolder,
        ToggleToolbar,
        ToggleReadOnly,
        ToggleFocus,
        ToggleTypewriter,
        ZoomIn,
        ZoomOut,
        ActualSize,
        Find,
        Replace,
        FindNext,
        FindPrevious,
        ReplaceNext,
        ReplaceAll,
        CloseSearch,
        Heading1,
        Heading2,
        Heading3,
        Heading4,
        Heading5,
        Heading6,
        Paragraph,
        PromoteHeading,
        DemoteHeading,
        InsertTable,
        TableRowAbove,
        TableRowBelow,
        TableColumnLeft,
        TableColumnRight,
        TableDeleteRow,
        TableDeleteColumn,
        TableAlignLeft,
        TableAlignCenter,
        TableAlignRight,
        InsertCodeBlock,
        Quote,
        OrderedList,
        BulletList,
        TaskList,
        ToggleTask,
        Indent,
        Outdent,
        ParagraphAbove,
        ParagraphBelow,
        HorizontalRule,
        FrontMatter,
        Bold,
        Italic,
        InlineCode,
        Strikethrough,
        Highlight,
        Link,
        InsertImage,
        ClearFormat,
        CopyPlain,
        SelectLine,
        MoveLineUp,
        MoveLineDown,
        DeleteLine,
        DeleteBlock,
        Minimize,
        ZoomWindow,
        Fullscreen,
        WordCount,
        QuickStart
    ]
);

#[derive(Clone, Copy, Default, PartialEq, Eq)]
pub struct MenuState {
    pub source: bool,
    pub dark: bool,
    pub sidebar: bool,
    pub outline: bool,
    pub tree: bool,
    pub toolbar: bool,
    pub read_only: bool,
    pub focus: bool,
    pub typewriter: bool,
}

fn checked(label: &str, enabled: bool) -> String {
    if enabled {
        format!("✓ {label}")
    } else {
        label.into()
    }
}

pub fn install(cx: &App, state: MenuState, recent: &[std::path::PathBuf]) {
    let recent_actions: Vec<Box<dyn Action>> = vec![
        Box::new(Recent1),
        Box::new(Recent2),
        Box::new(Recent3),
        Box::new(Recent4),
        Box::new(Recent5),
    ];
    let recent_items = recent
        .iter()
        .zip(recent_actions)
        .map(|(path, action)| MenuItem::Action {
            name: path.to_string_lossy().into_owned().into(),
            action,
            os_action: None,
        })
        .collect();
    cx.set_menus(vec![
        Menu {
            name: "Tiny MD".into(),
            items: vec![
                MenuItem::action("关于 Tiny MD", About),
                MenuItem::separator(),
                MenuItem::os_submenu("服务", SystemMenuType::Services),
                MenuItem::separator(),
                MenuItem::action("隐藏 Tiny MD", Hide),
                MenuItem::action("隐藏其他", HideOthers),
                MenuItem::action("显示全部", ShowAll),
                MenuItem::separator(),
                MenuItem::action("退出 Tiny MD", QuitApplication),
            ],
        },
        Menu {
            name: "文件".into(),
            items: vec![
                MenuItem::action("新建", NewDocument),
                MenuItem::action("新建窗口", NewWindow),
                MenuItem::separator(),
                MenuItem::action("打开…", OpenDocument),
                MenuItem::action("打开文件夹…", OpenFolder),
                MenuItem::submenu(Menu {
                    name: "打开最近文件".into(),
                    items: recent_items,
                }),
                MenuItem::separator(),
                MenuItem::action("保存", SaveDocument),
                MenuItem::action("另存为…", SaveDocumentAs),
                MenuItem::action("从磁盘重新加载", ReloadDocument),
                MenuItem::action("在 Finder 中显示", RevealDocument),
                MenuItem::separator(),
                MenuItem::action("关闭", CloseDocument),
            ],
        },
        Menu {
            name: "编辑".into(),
            items: vec![
                MenuItem::os_action("撤销", guise::actions::Undo, OsAction::Undo),
                MenuItem::os_action("重做", guise::actions::Redo, OsAction::Redo),
                MenuItem::separator(),
                MenuItem::os_action("剪切", guise::actions::Cut, OsAction::Cut),
                MenuItem::os_action("拷贝", guise::actions::Copy, OsAction::Copy),
                MenuItem::os_action("粘贴", guise::actions::Paste, OsAction::Paste),
                MenuItem::separator(),
                MenuItem::os_action("全选", guise::actions::SelectAll, OsAction::SelectAll),
                MenuItem::action("复制为纯文本", CopyPlain),
                MenuItem::action("选择当前行", SelectLine),
                MenuItem::separator(),
                MenuItem::action("上移该行", MoveLineUp),
                MenuItem::action("下移该行", MoveLineDown),
                MenuItem::action("删除当前行", DeleteLine),
                MenuItem::separator(),
                MenuItem::submenu(Menu {
                    name: "查找".into(),
                    items: vec![
                        MenuItem::action("查找…", Find),
                        MenuItem::action("查找下一个", FindNext),
                        MenuItem::action("查找上一个", FindPrevious),
                        MenuItem::action("替换…", Replace),
                    ],
                }),
            ],
        },
        Menu {
            name: "段落".into(),
            items: vec![
                MenuItem::action("一级标题", Heading1),
                MenuItem::action("二级标题", Heading2),
                MenuItem::action("三级标题", Heading3),
                MenuItem::action("四级标题", Heading4),
                MenuItem::action("五级标题", Heading5),
                MenuItem::action("六级标题", Heading6),
                MenuItem::separator(),
                MenuItem::action("段落", Paragraph),
                MenuItem::separator(),
                MenuItem::action("提升标题级别", PromoteHeading),
                MenuItem::action("降低标题级别", DemoteHeading),
                MenuItem::separator(),
                MenuItem::submenu(Menu {
                    name: "表格".into(),
                    items: vec![
                        MenuItem::action("插入表格", InsertTable),
                        MenuItem::separator(),
                        MenuItem::action("上方插入行", TableRowAbove),
                        MenuItem::action("下方插入行", TableRowBelow),
                        MenuItem::action("左侧插入列", TableColumnLeft),
                        MenuItem::action("右侧插入列", TableColumnRight),
                        MenuItem::separator(),
                        MenuItem::action("左对齐", TableAlignLeft),
                        MenuItem::action("居中对齐", TableAlignCenter),
                        MenuItem::action("右对齐", TableAlignRight),
                        MenuItem::separator(),
                        MenuItem::action("删除行", TableDeleteRow),
                        MenuItem::action("删除列", TableDeleteColumn),
                    ],
                }),
                MenuItem::action("代码块", InsertCodeBlock),
                MenuItem::action("引用", Quote),
                MenuItem::separator(),
                MenuItem::action("有序列表", OrderedList),
                MenuItem::action("无序列表", BulletList),
                MenuItem::action("任务列表", TaskList),
                MenuItem::action("切换任务状态", ToggleTask),
                MenuItem::submenu(Menu {
                    name: "列表缩进".into(),
                    items: vec![
                        MenuItem::action("增加缩进", Indent),
                        MenuItem::action("减少缩进", Outdent),
                    ],
                }),
                MenuItem::separator(),
                MenuItem::action("在上方插入段落", ParagraphAbove),
                MenuItem::action("在下方插入段落", ParagraphBelow),
                MenuItem::separator(),
                MenuItem::action("水平分割线", HorizontalRule),
                MenuItem::action("YAML Front Matter", FrontMatter),
            ],
        },
        Menu {
            name: "格式".into(),
            items: vec![
                MenuItem::action("加粗", Bold),
                MenuItem::action("斜体", Italic),
                MenuItem::action("代码", InlineCode),
                MenuItem::separator(),
                MenuItem::action("删除线", Strikethrough),
                MenuItem::action("高亮", Highlight),
                MenuItem::separator(),
                MenuItem::action("超链接", Link),
                MenuItem::action("插入图片链接…", InsertImage),
                MenuItem::separator(),
                MenuItem::action("清除样式", ClearFormat),
            ],
        },
        Menu {
            name: "显示".into(),
            items: vec![
                MenuItem::action(checked("源代码模式", state.source), ToggleSource),
                MenuItem::action(checked("只读模式", state.read_only), ToggleReadOnly),
                MenuItem::separator(),
                MenuItem::action(checked("专注模式", state.focus), ToggleFocus),
                MenuItem::action(checked("打字机模式", state.typewriter), ToggleTypewriter),
                MenuItem::separator(),
                MenuItem::action(checked("工具栏", state.toolbar), ToggleToolbar),
                MenuItem::action(checked("显示 / 隐藏侧边栏", state.sidebar), ToggleSidebar),
                MenuItem::action(
                    checked("文档列表", state.sidebar && !state.outline && !state.tree),
                    ShowDocuments,
                ),
                MenuItem::action(checked("大纲", state.sidebar && state.outline), ShowOutline),
                MenuItem::action(checked("文档树", state.sidebar && state.tree), ShowTree),
                MenuItem::action("字数统计", WordCount),
                MenuItem::separator(),
                MenuItem::action("实际大小", ActualSize),
                MenuItem::action("放大", ZoomIn),
                MenuItem::action("缩小", ZoomOut),
                MenuItem::separator(),
                MenuItem::action("全屏", Fullscreen),
            ],
        },
        Menu {
            name: "主题".into(),
            items: vec![
                MenuItem::action(checked("浅色", !state.dark), LightTheme),
                MenuItem::action(checked("深色", state.dark), DarkTheme),
            ],
        },
        Menu {
            name: "窗口".into(),
            items: vec![
                MenuItem::action("最小化", Minimize),
                MenuItem::action("缩放", ZoomWindow),
                MenuItem::action("全屏", Fullscreen),
            ],
        },
        Menu {
            name: "帮助".into(),
            items: vec![
                MenuItem::action("快速入门", QuickStart),
                MenuItem::action("关于 Tiny MD", About),
            ],
        },
    ]);
}

pub fn bind(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("cmd-n", NewDocument, None),
        KeyBinding::new("cmd-shift-n", NewWindow, None),
        KeyBinding::new("cmd-o", OpenDocument, None),
        KeyBinding::new("cmd-q", QuitApplication, None),
        KeyBinding::new("cmd-h", Hide, None),
        KeyBinding::new("cmd-alt-h", HideOthers, None),
    ]);
    macro_rules! keys { ($($key:literal => $action:expr),* $(,)?) => { cx.bind_keys([$ (KeyBinding::new($key, $action, Some("TinyMd"))),*]); }; }
    keys![
        "cmd-n" => NewDocument, "cmd-shift-n" => NewWindow, "cmd-o" => OpenDocument,
        "cmd-s" => SaveDocument, "cmd-shift-s" => SaveDocumentAs,
        "cmd-w" => CloseDocument, "cmd-q" => QuitApplication,
        "cmd-/" => ToggleSource, "cmd-shift-m" => ToggleSource,
        "cmd-shift-t" => ToggleTheme, "cmd-shift-l" => ToggleSidebar,
        "ctrl-cmd-1" => ShowOutline, "ctrl-cmd-2" => ShowDocuments,
        "f8" => ToggleFocus, "f9" => ToggleTypewriter,
        "cmd-f" => Find, "cmd-alt-f" => Replace, "cmd-g" => FindNext, "cmd-shift-g" => FindPrevious,
        "cmd-1" => Heading1, "cmd-2" => Heading2, "cmd-3" => Heading3,
        "cmd-4" => Heading4, "cmd-5" => Heading5, "cmd-6" => Heading6, "cmd-0" => Paragraph,
        "cmd-=" => PromoteHeading, "cmd--" => DemoteHeading,
        "cmd-alt-c" => InsertCodeBlock, "cmd-alt-q" => Quote, "cmd-alt-o" => OrderedList,
        "cmd-alt-u" => BulletList, "cmd-alt-x" => TaskList, "cmd-enter" => ToggleTask,
        "cmd-b" => Bold, "cmd-i" => Italic, "ctrl-`" => InlineCode,
        "ctrl-shift-`" => Strikethrough, "cmd-k" => Link, "cmd-backslash" => ClearFormat,
        "alt-up" => MoveLineUp, "alt-down" => MoveLineDown,
        "cmd-shift-=" => ZoomIn, "cmd-shift--" => ZoomOut, "cmd-shift-0" => ActualSize,
        "cmd-m" => Minimize, "ctrl-cmd-f" => Fullscreen,
    ];
    cx.bind_keys([
        KeyBinding::new("cmd-z", guise::actions::Undo, Some("TinyMdMarkdown")),
        KeyBinding::new("cmd-shift-z", guise::actions::Redo, Some("TinyMdMarkdown")),
        KeyBinding::new("cmd-x", guise::actions::Cut, Some("TinyMdMarkdown")),
        KeyBinding::new("cmd-c", guise::actions::Copy, Some("TinyMdMarkdown")),
        KeyBinding::new("cmd-v", guise::actions::Paste, Some("TinyMdMarkdown")),
        KeyBinding::new("cmd-a", guise::actions::SelectAll, Some("TinyMdMarkdown")),
        KeyBinding::new("escape", CloseSearch, Some("TinyMd")),
    ]);
}

pub fn register_forwarding(cx: &mut App) {
    macro_rules! forward { ($($action:ty),* $(,)?) => { $(cx.on_action(|action: &$action, cx| { crate::forward_action(action, cx); });)* }; }
    forward![
        SaveDocument,
        SaveDocumentAs,
        ReloadDocument,
        RevealDocument,
        CloseDocument,
        About,
        Recent1,
        Recent2,
        Recent3,
        Recent4,
        Recent5,
        ToggleSource,
        ToggleTheme,
        LightTheme,
        DarkTheme,
        ToggleSidebar,
        ShowDocuments,
        ShowOutline,
        ShowTree,
        OpenFolder,
        ToggleToolbar,
        ToggleReadOnly,
        ToggleFocus,
        ToggleTypewriter,
        ZoomIn,
        ZoomOut,
        ActualSize,
        Find,
        Replace,
        FindNext,
        FindPrevious,
        ReplaceNext,
        ReplaceAll,
        CloseSearch,
        Heading1,
        Heading2,
        Heading3,
        Heading4,
        Heading5,
        Heading6,
        Paragraph,
        PromoteHeading,
        DemoteHeading,
        InsertTable,
        InsertCodeBlock,
        Quote,
        OrderedList,
        BulletList,
        TaskList,
        ToggleTask,
        Indent,
        Outdent,
        ParagraphAbove,
        ParagraphBelow,
        HorizontalRule,
        FrontMatter,
        Bold,
        Italic,
        InlineCode,
        Strikethrough,
        Highlight,
        Link,
        InsertImage,
        ClearFormat,
        CopyPlain,
        SelectLine,
        MoveLineUp,
        MoveLineDown,
        DeleteLine,
        DeleteBlock,
        Minimize,
        ZoomWindow,
        Fullscreen,
        WordCount,
        QuickStart,
        TableRowAbove,
        TableRowBelow,
        TableColumnLeft,
        TableColumnRight,
        TableDeleteRow,
        TableDeleteColumn,
        TableAlignLeft,
        TableAlignCenter,
        TableAlignRight,
        guise::actions::Copy,
        guise::actions::Cut,
        guise::actions::Paste,
        guise::actions::SelectAll,
        guise::actions::Undo,
        guise::actions::Redo,
    ];
}
